CREATE TABLE TB_SCHEDULE
(
S_ID  CHAR(10) PRIMARY KEY,
TITLE   VARCHAR2(20),
S_DATE    DATE,
S_CONTENT VARCHAR2(50)
);
COMMENT ON COLUMN TB_SCHEDULE.S_ID IS '일정번호';
COMMENT ON COLUMN TB_SCHEDULE.TITLE IS '제목';
COMMENT ON COLUMN TB_SCHEDULE.S_DATE IS '날짜';
COMMENT ON COLUMN TB_SCHEDULE.S_CONTENT IS '내용';
COMMIT;