INSERT INTO USER_ACCOUNT
VALUES (LPAD(SEQ_ACC.NEXTVAL, 5,0),'930216-1111000',DEFAULT,'01112341234','석호',SYSDATE,'tjrghekt','1234');
INSERT INTO USER_ACCOUNT
VALUES (LPAD(SEQ_ACC.NEXTVAL, 5,0),'910216-1111000',DEFAULT,'01112341234','선용',SYSDATE,'sungod','1234');
INSERT INTO USER_ACCOUNT
VALUES (LPAD(SEQ_ACC.NEXTVAL, 5,0),'910119-1111000',DEFAULT,'01112341234','동욱',SYSDATE,'uksuks','1234');
INSERT INTO USER_ACCOUNT
VALUES (LPAD(SEQ_ACC.NEXTVAL, 5,0),'900726-1111000',DEFAULT,'01112341234','성수',SYSDATE,'godsung','1234');
INSERT INTO USER_ACCOUNT
VALUES (LPAD(SEQ_ACC.NEXTVAL, 5,0),'920513-1111000',DEFAULT,'01112341234','정은',SYSDATE,'devje','1234');
INSERT INTO USER_ACCOUNT
VALUES (LPAD(SEQ_ACC.NEXTVAL, 5,0),'910226-1111000',DEFAULT,'01112341234','민경',SYSDATE,'mk1234','1234');
--DELETE USER_ACCOUNT;
CREATE TABLE USER_ACCOUNT
(
ACC_NUMBER CHAR(5) ,
SSN	CHAR(14),
BAL	NUMBER DEFAULT 0,
PHONE VARCHAR2(11) NOT NULL,
U_NAME VARCHAR2(20) NOT NULL,
ESTDATE DATE NOT NULL,
ID	VARCHAR2(12),
PASSWORD VARCHAR2(15),
CONSTRAINTS PK_ACCOUNT PRIMARY KEY(ACC_NUMBER, ID)
);
DROP TABLE USER_ACCOUNT;

CREATE SEQUENCE SEQ_ACC
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;


COMMENT ON COLUMN USER_ACCOUNT.ACC_NUMBER IS '계좌 번호';
COMMENT ON COLUMN USER_ACCOUNT.SSN IS '주민등록번호';
COMMENT ON COLUMN USER_ACCOUNT.BAL IS '현재 잔액';
COMMENT ON COLUMN USER_ACCOUNT.U_NAME IS '이름';
COMMENT ON COLUMN USER_ACCOUNT.ESTDATE IS '통장 개설 날짜';
COMMENT ON COLUMN USER_ACCOUNT.ID IS '아이디';
COMMENT ON COLUMN USER_ACCOUNT.PASSWORD IS '비밀번호';
COMMENT ON COLUMN USER_ACCOUNT.PHONE IS '핸드폰';


SELECT * FROM USER_ACCOUNT;

DROP TABLE BANK_LOG;
CREATE TABLE BANK_LOG
(
ID VARCHAR(12) ,
RECEIVER_ID VARCHAR(12),
EX_DATE DATE NOT NULL,
DEPOSIT NUMBER,
WITHDRAW NUMBER,
LOG_TYPE NUMBER(1),
USER_COMMENT VARCHAR2(50),
ACC_NUMBER CHAR(5),
RCC_NUMBER CHAR(5)
);

COMMENT ON COLUMN BANK_LOG.ID IS '아이디';
COMMENT ON COLUMN BANK_LOG.RECEIVER_ID IS '받는사람 아이디';
COMMENT ON COLUMN BANK_LOG.EX_DATE IS '거래일시';
COMMENT ON COLUMN BANK_LOG.DEPOSIT IS '입금액';
COMMENT ON COLUMN BANK_LOG.WITHDRAW IS '출금액';
COMMENT ON COLUMN BANK_LOG.USER_COMMENT IS '메세지';
COMMENT ON COLUMN BANK_LOG.LOG_TYPE IS '타입[1.입금/2.출금/3.송금]';
COMMENT ON COLUMN BANK_LOG.ACC_NUMBER IS '사용 계좌';
COMMENT ON COLUMN BANK_LOG.RCC_NUMBER IS '받는 사람 계좌번호';


COMMIT;
delete from user_account where id = 'tjrghekt';
select id from user_account where id = 'tjrghekt' and password = '1234';

select * from bank_log where id = 'tjrghekt' and log_type = 1;
select to_char(ex_date,'RRRR/MM/DD HH:MI:SS'), withdraw, log_type, user_comment, acc_number, rcc_number from bank_log where acc_number = '00041' and log_type in (2,3);
select to_char(ex_date,'RRRR/MM/DD HH:MI:SS') AS LDATE, deposit from bank_log where id = 'tjrghekt' and log_type = 1;
select to_char(ex_date,'RRRR/MM/DD HH:MI:SS') , DEPOSIT FROM BANK_LOG where id = 'tjrghekt' and log_type = 1;
select to_char(ex_date,'RRRR/MM/DD HH:MI:SS'), withdraw from bank_log where id = 'tjrghekt' and log_type in (2,3);
delete from BANK_LOG;





















