DROP TABLE PRODUCT;

CREATE TABLE PRODUCT (
PRODUCT_ID VARCHAR2(20) PRIMARY KEY,
P_NAME VARCHAR2(20) NOT NULL,
PRICE NUMBER NOT NULL,
DESCRIPTION VARCHAR2(20)
                );
COMMIT;
SELECT * FROM PRODUCT;
UPDATE PRODUCT SET PRICE = 1200000 WHERE PRODUCT_ID = 'pc_ibm';
ROLLBACK;

select * from product where p_name like '%samsung%';

